language: python
python:
  - '3.6'
install:
  - pip install -r requirements-travis.txt
services:
  - docker
before_script: 
  - pip install docker-compose
  - docker start mysql
  - cd app
script:
  - docker-compose up
  - sleep 50
  - docker-compose down
