language: python
python:
  - '3.6'
install:
  - pip install -r requirements-travis.txt
services:
  - docker
  - mysql
before_script: 
  - pip install docker-compose
  - docker pull mysql:5.7.23
  - mkdir -p ~/cs4501/db
  - docker network create backend
  - docker run --network=backend --name mysql -d -e MYSQL_ROOT_PASSWORD='$3cureUS' -v ~/cs4501/db:/var/lib/mysql  mysql:5.7.23
  - sleep 20
  - docker run --network=backend -it --name mysql-cmdline --link mysql:db mysql:5.7.23
    mysql -uroot -p'$3cureUS' -h db -e "CREATE USER 'www'@'%' IDENTIFIED BY '\$3cureUS';CREATE DATABASE cs4501 CHARACTER SET utf8; GRANT ALL PRIVILEGES ON *.* TO 'www'@'%';"
  - docker start mysql
  - cd app
  - docker-compose up -d
  - sleep 40
  - docker-compose stop
  - docker ps -a
  - docker network ls
  - docker network connect app_backend mysql
script:
  - docker-compose up -d
  - sleep 40
after_script:
  - docker ps -a
  - docker stop mysql
  - docker-compose down -v
