language: python
python:
  - '3.6'
install:
  - pip install -r requirements-travis.txt
services:
  - docker
before_script: 
  - pip install docker-compose
  - docker pull mysql:latest
  - docker run --name mysql -d -e MYSQL_ROOT_PASSWORD='$3cureUS' mysql:latest
  - docker run -it --name mysql-cmdline --link mysql:db mysql:latest bash
  - mysql -uroot -p'$3cureUS' -h db
  - create user 'www'@'%' identified with mysql_native_password by '$3cureUS';
  - create database cs4501 character set utf8;
  - grant all on cs4501.* to 'www'@'%';
  - exit
  - cd app
script:
  - docker-compose up
  - sleep 20
  - docker-compose down
