# Generated by Django 2.2.4 on 2020-02-06 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_school_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='School',
            new_name='Schools',
        ),
    ]
