# Generated by Django 2.2.4 on 2020-05-06 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_recommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Post'),
        ),
    ]
