# Generated by Django 2.2.4 on 2020-02-28 21:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200228_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 28, 21, 24, 36, 632860, tzinfo=utc)),
        ),
    ]
