# Generated by Django 2.2.4 on 2020-02-29 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200228_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='computing_id',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('content', models.TextField(default='', max_length=3000)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_nums', models.IntegerField()),
                ('pickup_address', models.CharField(default='', max_length=300)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
