# Generated by Django 2.2.4 on 2020-03-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummyuser',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='dummyuser',
            name='computing_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='dummyuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='dummyuser',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dummyuser',
            name='last_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dummyuser',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
